<a href="https://colab.research.google.com/github/610Aditi/Training/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Topic : NLP(**Natural Language Processing**)

1) Tokenization :

2) Embedding (Word2Vec , Glove)

3) Bag-of-Words and TF-IDF

**Natural Language Processing :** It is the branch of artifical intelligence that help to understand , interperte , generate human language.



*  Without NLP
*  With NLP

**Application :**

Search Engines ,Chatbots ,Email fittering ,Speed of Text ,Language translation ,grammer correction , Sentiment Analysis ,Text Samarization.

Basic NLP Steps :  
**Tokenization :**


*   Remove Stopwords
*   Stemming
*   Vectorization
*   Model Prediction

**Basic Input -**
"NLP is the best branch of AI."

**After Tokenizaton -**
"NLP", "is","the", "best" ,"branch", "of", "AI."

In [5]:
# NLTK is a python library that is used for natuaral language processing
import nltk
try:
    nltk.data.find("tokenizers/punkt")
except LookupError:
    nltk.download("punkt")

from nltk.tokenize import word_tokenize
data = "NLP is the best branch of AI."
Processed_data = word_tokenize(data)
print(Processed_data)

['NLP', 'is', 'the', 'best', 'branch', 'of', 'AI', '.']


In [6]:
#data = "Curves can be represented by implicit, explicit, or parametric equations. Implicit equations cannot be used in computer graphics, explicit can, but not always in a convenient way. Parametric equations suit naturally the work with computers."
data = "He is working on google colab since 2004 ."
Processed_data = word_tokenize(data)
print(Processed_data)
print(len(Processed_data))


['He', 'is', 'working', 'on', 'google', 'colab', 'since', '2004', '.']
9


In [7]:
from nltk.corpus import stopwords
nltk.download("stopwords")
stop_words = set(stopwords.words("english"))
filtered_sentence = []
for w in Processed_data:
    if w.lower() not in stop_words:
        filtered_sentence.append(Processed_data)
print(len(filtered_sentence))


6


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [8]:
# Stemming : Reduces words to there base root or forms.
from nltk.stem import PorterStemmer

In [9]:
Stemmer = PorterStemmer()
data1 = [Stemmer.stem(w) for w in Processed_data]
print(data1)



['he', 'is', 'work', 'on', 'googl', 'colab', 'sinc', '2004', '.']


In [10]:
# Vectorization : It is a techineque that convert text into numeric vector
# Types of Vectorization:
# Bag of Words , TF IDF Vectorization ,Embedding
#Bag of words : It count the words that how many times it appears in the whole document

from sklearn.feature_extraction.text import CountVectorizer
text = ["I have NLP Books Books","NLP Books In PDF Format","NLP is important Branch of AI , ITs Important to have Knowledge of AI."]

vector = CountVectorizer()
New_text = vector.fit_transform(text)
print(vector.get_feature_names_out())
print(New_text.toarray())

['ai' 'books' 'branch' 'format' 'have' 'important' 'in' 'is' 'its'
 'knowledge' 'nlp' 'of' 'pdf' 'to']
[[0 2 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 1 0 0 1 0 0 0 1 0 1 0]
 [2 0 1 0 1 2 0 1 1 1 1 2 0 1]]


In [11]:
# TF-IDF: TF is how frequently it appear in the document.
# IDF : how rate it appear in the document.
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
vector = tfidf.fit_transform(text)
print(tfidf.get_feature_names_out())
print(vector.toarray())

['ai' 'books' 'branch' 'format' 'have' 'important' 'in' 'is' 'its'
 'knowledge' 'nlp' 'of' 'pdf' 'to']
[[0.         0.84492112 0.         0.         0.42246056 0.
  0.         0.         0.         0.         0.32807831 0.
  0.         0.        ]
 [0.         0.38376993 0.         0.50461134 0.         0.
  0.50461134 0.         0.         0.         0.29803159 0.
  0.50461134 0.        ]
 [0.47236035 0.         0.23618018 0.         0.17962111 0.47236035
  0.         0.23618018 0.23618018 0.23618018 0.13949182 0.47236035
  0.         0.23618018]]


In [1]:
%pip install gensim

In [2]:
# Embedding (Word2Vec , Glove ): Word Embedding is mapped each word to a vector of real number.
import gensim.downloader as api
word2vec_model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
vector1 = word2vec_model["computer"]
print(vector1[:10])
print(word2vec_model)

simi = word2vec_model.most_similar("computer")
for i in simi:
  print(i)


[ 0.10742188 -0.20117188  0.12304688  0.21191406 -0.09130859  0.21679688
 -0.13183594  0.08300781  0.20214844  0.04785156]
KeyedVectors<vector_size=300, 3000000 keys>
('computers', 0.7979379892349243)
('laptop', 0.6640493273735046)
('laptop_computer', 0.6548868417739868)
('Computer', 0.647333562374115)
('com_puter', 0.6082080006599426)
('technician_Leonard_Luchko', 0.5662748217582703)
('mainframes_minicomputers', 0.5617720484733582)
('laptop_computers', 0.5585449934005737)
('PC', 0.5539618730545044)
('maker_Dell_DELL.O', 0.5519254207611084)


In [4]:
model2 = api.load("glove-wiki-gigaword-50")


[==================================================] 100.0% 66.0/66.0MB downloaded


In [5]:
vector2 = model2["computer"]
print(vector2[:10])
print(model2)

simi2 = model2.most_similar("computer")
for j in simi2:
  print(j)


[ 0.079084 -0.81504   1.7901    0.91653   0.10797  -0.55628  -0.84427
 -1.4951    0.13418   0.63627 ]
KeyedVectors<vector_size=50, 400000 keys>
('computers', 0.9165045022964478)
('software', 0.8814992904663086)
('technology', 0.852556049823761)
('electronic', 0.812586784362793)
('internet', 0.8060455322265625)
('computing', 0.802603542804718)
('devices', 0.8016185760498047)
('digital', 0.7991793751716614)
('applications', 0.7912740707397461)
('pc', 0.7883159518241882)


**4) Attention** is a technique that allow a model to focus on specific words in a sentence  when performing a task.

** Why we need Attention **

Attention leads the model to attend the sequence even for apart of words.

**Types :**


*   Self Attention
*   Global Attention
*   Local Attention
*   Multihead Attention

**Self Attention :**

Q : what i want to know (queries).

K : what each words decode/effect.

V : word representation.


In [7]:
!pip install torch

In [8]:
import torch
import torch.nn as nn
import torch.functional as fn

text = ["The","Man","Work"]
e_d = 8
words_to_index = {w:i for i,w in enumerate(text)}
index_to_words = {i:w for i,w in enumerate(text)}



In [9]:
print(words_to_index)

{'The': 0, 'Man': 1, 'Work': 2}


In [11]:
#print(index_to_words)
idx_words = torch.tensor([words_to_index[w] for w in text],dtype=torch.long)
print(idx_words)

tensor([0, 1, 2])


In [14]:
embed = nn.Embedding(num_embeddings=len(words_to_index),embedding_dim=e_d)



In [16]:
embeded= embed(idx_words)
embeded = embeded.unsqueeze(0)
print(embeded)

tensor([[[ 0.9677, -0.6863, -0.3008, -0.4824, -1.2882, -1.9787, -0.6491,
          -1.9602],
         [ 1.0126,  0.8047,  0.7653,  0.7078,  0.7379,  0.1020, -1.6547,
          -0.2611],
         [ 0.4364,  0.2187,  0.3832,  2.1965, -1.0348, -0.8579, -0.4617,
          -0.3447]]], grad_fn=<UnsqueezeBackward0>)


In [17]:
num_head = 2
multi_head = nn.MultiheadAttention(embed_dim=e_d,num_heads=num_head,batch_first=True)

In [18]:
print(multi_head)

MultiheadAttention(
  (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)
)


In [20]:
a_output,a_weights=multi_head(embeded,embeded,embeded)
print(a_output)
print(a_weights)

tensor([[[ 0.1495, -0.2471, -0.1526, -0.0490, -0.0299, -0.2354,  0.1486,
           0.2971],
         [ 0.3781, -0.1267, -0.1950, -0.0320, -0.2279, -0.3994, -0.1131,
           0.1583],
         [ 0.0808, -0.2978, -0.1151, -0.0271,  0.0047, -0.2250,  0.1959,
           0.3272]]], grad_fn=<TransposeBackward0>)
tensor([[[0.4008, 0.2672, 0.3320],
         [0.5605, 0.2187, 0.2209],
         [0.3122, 0.2513, 0.4365]]], grad_fn=<MeanBackward1>)


In [22]:
a_weights.squeeze(0).detach()

tensor([[0.4008, 0.2672, 0.3320],
        [0.5605, 0.2187, 0.2209],
        [0.3122, 0.2513, 0.4365]])

In [23]:
a_output.squeeze(0).detach()


tensor([[ 0.1495, -0.2471, -0.1526, -0.0490, -0.0299, -0.2354,  0.1486,  0.2971],
        [ 0.3781, -0.1267, -0.1950, -0.0320, -0.2279, -0.3994, -0.1131,  0.1583],
        [ 0.0808, -0.2978, -0.1151, -0.0271,  0.0047, -0.2250,  0.1959,  0.3272]])

**Transformers**:it follows a encoder-decoder design.Also called **Hugging Phase**.

Encoder basically reads the input sentence and build the relation.(BERT Models)

Decoder basically takes the representation as a output.(GPT Models)


In [24]:
#"The Man Works"
!pip install transformers sentecepiece


ERROR: Could not find a version that satisfies the requirement sentecepiece (from versions: none)
ERROR: No matching distribution found for sentecepiece


In [31]:
import torch
from transformers import MarianMTModel, MarianTokenizer

In [45]:
model = "Helsinki-NLP/opus-mt-en-hi"
tok = MarianTokenizer.from_pretrained(model)
models = MarianMTModel.from_pretrained(model)

input_text = ["The Man Works"]
token_input = tok(input_text,return_tensors="pt",padding = True,Truncation=True)

print(token_input)

Keyword arguments {'Truncation': True} not recognized.


{'input_ids': tensor([[   81,  4221, 24741,     0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


In [46]:
translate = models.generate(**token_input)

In [47]:
translate

tensor([[61949,   720,   182,   161,     5,     0]])

In [48]:
# decode
output = tok.batch_decode(translate,skip_special_tokens=True)
output

['मनुष्य काम करता है']

In [ ]:
#  convert model into API


**Library :**

numpy ,pandas,seaborn ,sklearn ,pytouch ,tensorflow-keras
,NLTHK,transformer - hugging phase library ,gensim,langpedect,open_cv,pillow(PIL), touch vision ,Fast AI -used in deeplearning