<a href="https://colab.research.google.com/github/610Aditi/Training/blob/main/Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
sample_arr = np.arange(1,11)
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sample_list_of_lists = ([[1,2,3],[4,5,6],[7,8,9]])
np.array(sample_list_of_lists)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [ ]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.linspace(0,10,5)  #generate equal distance 10 number

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3) # it will generate random values uniformly

array([0.90192952, 0.53519007, 0.52816434])

In [ ]:
np.random.rand(3,3)

array([[0.89137283, 0.24249804, 0.16296616],
       [0.28972159, 0.28857437, 0.20080326],
       [0.90772125, 0.41944491, 0.81587468]])

In [ ]:
b = np.random.randn(3,3)
b

array([[ 0.70798604,  1.80951392,  1.41661849],
       [-0.99059887,  1.38048593,  0.42772498],
       [ 1.58645473,  1.32762063, -0.72210296]])

In [ ]:
b.shape

(3, 3)

In [ ]:
b.dtype

dtype('float64')

In [ ]:
random_arr = np.random.randint(0,10,20)
random_arr

array([4, 7, 0, 1, 5, 3, 1, 5, 5, 2, 6, 7, 5, 1, 9, 2, 0, 7, 3, 1])

In [ ]:
random_arr.max()


np.int64(9)

In [ ]:
ab=(4,)  # it will be tuple
type(ab)

tuple

In [ ]:
a=(1)  #it is not tuple
type(a)


int

In [ ]:
random_arr.argmin()

np.int64(2)

In [ ]:
random_arr.argmin()

np.int64(2)

In [ ]:
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sample_arr[2]

np.int64(3)

In [ ]:
sample_arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
sample_mat = np.array([[1,2,7],[3,4,9],[5,6,8]])

In [ ]:
sample_mat

array([[1, 2, 7],
       [3, 4, 9],
       [5, 6, 8]])

In [ ]:
sample_mat[0]

array([1, 2, 7])

In [ ]:
sample_mat[1][2]

np.int64(9)

In [ ]:
sample_mat[1,2]

np.int64(9)

In [ ]:
sample_mat[1:2]

array([[3, 4, 9]])

In [ ]:
sample_mat[:2,1:]

array([[2, 7],
       [4, 9]])

In [ ]:
sample_mat[1,1:]

array([4, 9])

In [ ]:
sample_mat[0:5]

array([[1, 2, 7],
       [3, 4, 9],
       [5, 6, 8]])

In [ ]:
sample_arr[0:3] = 400
sample_arr

array([400, 400, 400,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
print(id(sample_arr[0:5]))
slice_Of_sample_arr = sample_arr[0:5]
s=slice_Of_sample_arr
print(id(slice_Of_sample_arr))
print(id(sample_arr))
print(id(s))


140512446553936
140512446554992
140512457110704
140512446554992


In [ ]:
slice_Of_sample_arr[:] = 500
slice_Of_sample_arr

array([500, 500, 500, 500, 500])

In [ ]:
sample_arr

array([500, 500, 500, 500, 500,   6,   7,   8,   9,  10])

In [ ]:
sample_arr = np.arange(1,11)
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
boolean_arr = sample_arr > 5
print(boolean_arr)
type(boolean_arr)

[False False False False False  True  True  True  True  True]


numpy.ndarray

In [ ]:
sample_arr[boolean_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
sample_arr[sample_arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
print(np.add(a,b))
#print(np.subtract(a,b))
#print(np.multiply(a,b))
#print(np.divide(a,b))
#print(np.mod(a,b))

[[1.70798604 2.80951392 2.41661849]
 [0.00940113 2.38048593 1.42772498]
 [2.58645473 2.32762063 0.27789704]]


In [ ]:
arr_2D = np.arange(50).reshape(5,10)

In [ ]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
a = np.arange(0,11)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.dot(a,100)
b
# c = np.cross(b,a)
# c


array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

implement bubble sort in python

In [ ]:
#3d vectors
a=np.array([1,2,3])
b=np.array([4,5,6])
cross_product_3d = np.cross(a,b)
print(f"cross product of a and b is {cross_product_3d}")



#2d vectors
x=np.array([1,2])
y=np.array([4,5])
cross_product_2d = np.cross(a,b)
print(f"cross product of a and b is {cross_product_2d}")


cross product of a and b is [-3  6 -3]
cross product of a and b is [-3  6 -3]


In [ ]:
print(a/a)

[1. 1. 1.]


In [ ]:
print(1/a)

[1.         0.5        0.33333333]


In [ ]:
import numpy
cofficient = [12,3,4,5,6,7,10]
polynomialExp = numpy.poly1d(cofficient)
print("type of polynomial = ",type(polynomialExp))
print("Polynomial expression is : ",polynomialExp)
print(polynomialExp)
x=2
result = polynomialExp(x)
print(result)
print('======================================================================')

# coff = numpy.array([12,3,4,5,6,7,10])
# poly = numpy.poly

type of polynomial =  <class 'numpy.poly1d'>
Polynomial expression is :      6     5     4     3     2
12 x + 3 x + 4 x + 5 x + 6 x + 7 x + 10
    6     5     4     3     2
12 x + 3 x + 4 x + 5 x + 6 x + 7 x + 10
1016


In [ ]:
import numpy
a=numpy.matrix(((10,20,30),(40,50,60)))
print("a: \n ",a)
b=numpy.matrix_transpose(a)
print("transpose of a: \n",b)

a: 
  [[10 20 30]
 [40 50 60]]
transpose of a: 
 [[10 40]
 [20 50]
 [30 60]]


In [ ]:
import numpy
a= numpy.matrix(((10,20,30),(40,50,60),(70,80,90),(100,110,120)))
b= numpy.hsplit(a,3)
print("a\n",a)
print("b\n",b)
c=b[0]
d=b[1]
e=b[2]
print("c\n",c)
print("d\n",d)

a
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
b
 [matrix([[ 10],
        [ 40],
        [ 70],
        [100]]), matrix([[ 20],
        [ 50],
        [ 80],
        [110]]), matrix([[ 30],
        [ 60],
        [ 90],
        [120]])]
c
 [[ 10]
 [ 40]
 [ 70]
 [100]]
d
 [[ 20]
 [ 50]
 [ 80]
 [110]]


**PANDAS **


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
labels =["a","b","c"]
print(labels)
my_data = [10, 20, 30]
print(my_data)
arr = np.array(my_data)
print(arr)
d = {'a':10, 'b':20, 'c':30}
print(d)

['a', 'b', 'c']
[10, 20, 30]
[10 20 30]
{'a': 10, 'b': 20, 'c': 30}


In [ ]:
#This will explicitly define indexes
print(type(pd.Series(data = my_data)))

#define index
pd.Series(data = my_data, index = labels)

p_series = pd.Series(arr)
print(p_series)

pd.Series(arr, labels)


<class 'pandas.core.series.Series'>
0    10
1    20
2    30
dtype: int64


a    10
b    20
c    30
dtype: int64

In [ ]:
#Using Dictonary
pd.Series(d)
print(d)


{'a': 10, 'b': 20, 'c': 30}


In [ ]:
#Series can hold any kind of data object with Python like string, integer
print(pd.Series(labels))
print(pd.Series(data = labels))

0    a
1    b
2    c
dtype: object
0    a
1    b
2    c
dtype: object


In [ ]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
s1 = pd.Series([1, 2, 3, 4], ['A', 'B', 'C', 'D'])
print(s1)
s2 = pd.Series([1, 2, 5, 4], ['A', 'B', 'BB', 'D'])
print(s2)
print(s1['A'])

A    1
B    2
C    3
D    4
dtype: int64
A     1
B     2
BB    5
D     4
dtype: int64
1


In [ ]:
"""     All operations in Series are based on Index
        In order to retrain all possible information
        Pandas will convert int values to float           """
print(s1+s2)

A     2.0
B     4.0
BB    NaN
C     NaN
D     8.0
dtype: float64


In [ ]:
#Data Frame
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5, 4), ['A', 'B', 'C', 'D', 'E'], ['K', 'L', 'M', 'N'])
print(df)

          K         L         M         N
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [ ]:
print(df["K"])
print(type(df['K']))

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: K, dtype: float64
<class 'pandas.core.series.Series'>


In [ ]:
#Single column will return Series Object, multiple columns will return dataframe.
print(df[['K']])
print(type(df[['K']]))
print(df['L'])
print(type(df['L']))
print(df[['K', 'M']])
print(type(df[['K', 'M']]))
df["G"] = df['K'] + df['L']
print(df)

          K
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794
<class 'pandas.core.frame.DataFrame'>
A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: L, dtype: float64
<class 'pandas.core.series.Series'>
          K         M
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967
<class 'pandas.core.frame.DataFrame'>
          K         L         M         N         G
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552


In [ ]:
df = df.drop('G', axis = 1)
print(df)

          K         L         M         N
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [ ]:
#axis = 1 refer to columns
#axis = 0 refer to rows

#df = df.drop('E', axis = 0)
#print(df)

df.drop('K', axis = 1, inplace = True)
df

#inplace = False, Which is the default, then the operation is performed and it returns a copy of the object

L         M         N
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965
C  0.740122  0.528813 -0.589001
D -0.758872 -0.933237  0.955057
E  1.978757  2.605967  0.683509

In [ ]:
df = pd.DataFrame(randn(5, 4), ['A', 'B', 'C', 'D', 'E'], ['K', 'L', 'M', 'N'])
print(df)


          K         L         M         N
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652


In [ ]:
print(df<1)

      K      L     M      N
A  True  False  True   True
B  True   True  True   True
C  True   True  True   True
D  True   True  True   True
E  True  False  True  False


In [ ]:
#Assign and create new dataframe
#Condition applied on entrire datafrrame
boolean_df = df < 1
print(boolean_df) # this is new boolean dataframe
print(df[boolean_df]) # this is new dataframe
print("*"*50)
print("We can combine above two instructions in one step")
print(df[df<1])


      K      L     M      N
A  True  False  True   True
B  True   True  True   True
C  True   True  True   True
D  True   True  True   True
E  True  False  True  False
          K         L         M         N
A  0.302665       NaN -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773       NaN  0.238127       NaN
**************************************************
We can combine above two instructions in one step
          K         L         M         N
A  0.302665       NaN -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773       NaN  0.238127       NaN


In [ ]:
from numpy.random import randn
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['K','L','M','N'])
print(df)
print(df<1)

#Assign and create new dataframe
#Condition applied on the entrire

boolean_df = df < 1
print(boolean_df) # this is new boolean dataframe
print(df[boolean_df]) # this is new dataframe
print("*"*50)
print("We can combine above two instructions in one step")
print(df[df<1])


          K         L         M         N
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478
       K      L     M      N
A   True   True  True   True
B  False   True  True   True
C  False   True  True   True
D   True   True  True  False
E   True  False  True   True
       K      L     M      N
A   True   True  True   True
B  False   True  True   True
C  False   True  True   True
D   True   True  True  False
E   True  False  True   True
          K         L         M         N
A -0.993263  0.196800 -1.136645  0.000366
B       NaN -0.156598 -0.031579  0.649826
C       NaN -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769       NaN
E -0.925874       NaN -1.133817  0.610478
**************************************************
We can combine above two instructions in one step
          K         L         M         N
A -0.

In [ ]:
#Apply on columns
print(df['K'])
print(df['K']>0)
print(df[df['K']>0])#unlike the previous one,
#it will return rows where df['k']>0 id True

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: K, dtype: float64
A    False
B     True
C     True
D     True
E    False
Name: K, dtype: bool
          K         L         M         N
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810


In [ ]:
#Return rows where column value k
#happens to be less than 0 and returns values of column M

print(df[df['K']>0]['M'])
print(df[df['K']>0][['M','N']])

B   -0.031579
C   -0.755325
D    0.558769
Name: M, dtype: float64
          M         N
B -0.031579  0.649826
C -0.755325 -0.346419
D  0.558769  1.024810


In [ ]:
# Multiple Condition
#df[(df['K']>0)] and (df["M"]>0) # ambiguous and operation
# element -wise logical operators will do the needful
#TRUE AND TRUE
# TRUE AND FALSE
df["K"]>0
df[(df["K"]>0) & (df["M"]>0)]

#for OR use

df
print(df.reset_index()) #inplace param is false
                        #by default here
df

  index         K         L         M         N
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478


K         L         M         N
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [ ]:
#Selecting ROWS
print(df)
print("*"*50)
df.loc['A']
df.iloc[0]
df.loc['A','K']
print(df.shape)
print(df.loc['A'])
print(df.loc[['A','B'],['K','L']])

#test by providing tuple of tuple
#read about loc , iloc , ix , nunique in detail


          K         L         M         N
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478
**************************************************
(5, 4)
K   -0.993263
L    0.196800
M   -1.136645
N    0.000366
Name: A, dtype: float64
          K         L
A -0.993263  0.196800
B  1.025984 -0.156598


Read file

In [ ]:
import pandas as pd
df=pd.read_csv("/content/sample_data/video26_dataset_1.tsv", sep='\t')
print(df)
print(type(df))
print(df.shape)
print("df.columns: ",df.columns)
print("type(df.columns): ",type(df.columns))
print("df.dtypes: ", df.dtypes)
print("type(df.dtypes): ", type(df.dtypes))
print("*"*50)
print("df.info(): ",df.info())
country= df["country"]
print('country: ',country)
print('type(country)',type(country))
countries= set(country)  #set i.e. unique country
print(countries)
print("*"*50)
for c in countries: print(c)
a=df[["country","year"]]
print(a.head())
print(a.tail())
print("*"*50)
print('a.iloc[4] : ',a.iloc[4])   # iloc record at location/index 4
print("type(a.iloc[4]): ", type(a.iloc[4]))    #Single index for one row [1] returns a Pandas Series.
print("df.iloc[4]: ",df.iloc[4])
print("*"*50)
print(df.iloc[ :, 0])
# this will return all rows and first columns of data frame, list of indexes [[row, column]] returns a Pandas DataFrame.
print('type(df.iloc[ :, 0]): ',type(df.iloc[ :, 0]))
print("*"*50)
print(df.iloc[range(0,10,2)])
print("*"*50)
#pandas for SQL
print(df.groupby("country")["pop"].sum())


          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
(1704, 6)
df.columns:  Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')
type(df.columns):  <class 'pandas.core.indexes.

In [ ]:
import pandas
citiesDataFrame = pandas.DataFrame({"city_code":[1,2,3,4,5],"city_name":["Ujjain",'Indore','Banglore','Mumbai','Delhi']})
studentDataFrame = pandas.DataFrame({"student_rollno":[101,206,394,445,675],"student_name":["1",'2','3','4','5'],"city_code":[1,2,3,2,1]})
companyDataFrame = pandas.DataFrame({"company_id":[11,26,38,45,59],"city":[1,5,4,1,3]})
student_with_cities = pandas.merge(studentDataFrame,citiesDataFrame, how ="inner", on = ["city_code"])
print(student_with_cities)


   student_rollno student_name  city_code city_name
0             101            1          1    Ujjain
1             206            2          2    Indore
2             394            3          3  Banglore
3             445            4          2    Indore
4             675            5          1    Ujjain


In [ ]:
# if the both dataframe may have different name and city code
companyDataFrame = pandas.merge(citiesDataFrame,companyDataFrame, how ="inner", left_on = ["city_code"], right_on = ["city"])
print(companyDataFrame)

   city_code_x city_name_x  city_code_y city_name_y  company_id  city
0            1      Ujjain            1      Ujjain          11     1
1            1      Ujjain            1      Ujjain          45     1
2            3    Banglore            3    Banglore          59     3
3            4      Mumbai            4      Mumbai          38     4
4            5       Delhi            5       Delhi          26     5


In [ ]:
#read json file
import json
#opening json file
f = open("Employee.json")
#return JSON object as Distionary
employee_data = json.load(f)

#iteration through the Json list
for i in employee_data['emp_details']:
    print(i)
    print(type(i))
f.close()


{'emp_name': 'XYZ', 'email_id': 'XYZ@gmail.com', 'job_profile': 'Data Scientist'}
<class 'dict'>
{'emp_name': 'A', 'email_id': 'A@gmail.com', 'job_profile': 'Manager'}
<class 'dict'>


In [ ]:
series_data = pandas.Series([1,2,3,4,5])
result=series_data.agg([sum,len])
print(result)

sum    15
len     5
dtype: int64


/tmp/ipython-input-12-4117583373.py:2: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  result=series_data.agg([sum,len])


In [ ]:
def string_length(s):
    print("string_length called")
    return len(s)

In [ ]:
def int_length(i):
    print("int_legth called")
    return string_length(str(i))

In [ ]:

def get_length_of_elements(t):
  a=[]
  for x in t:
   if isinstance(x, int): a.append(int_length)
   if isinstance(x, str): a.append(string_length)
  return  length_of_element_iterator_factory(t,a)

class length_of_element_iterator_factory:
    def __init__(self, t, a):
       self.t=t
       self.a=a
    def __iter__(self):
       return length_of_element_iterator(self)

class length_of_element_iterator:
    def __init__(self, obj):
        self.t= obj.t
        self.a= obj.a
        self.index= 0
    def __next__(self):
        if self.index >= len(self.t):
           raise StopIteration
        k= self.a[self.index](self.t[self.index])
        self.index +=1
        return k


In [ ]:

x=(10,20,"Good", "Example of functional programming", 30)
b= get_length_of_elements(x)
print()
print()
print("called length of elements")
print()
print()
for i in b:
  print(i)



called length of elements


int_legth called
string_length called
2
int_legth called
string_length called
2
string_length called
4
string_length called
33
int_legth called
string_length called
2
